### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by Arteiii** [Arteiii/logging#1]
## TODO:

- [ ] fix reflection not working  
- [ ] add simple logging to the console

## Core

- [ ] add logging history with postgresql

## Protofile

- [ ] add authorization 
  - [ ] Register Application
  - [ ] Register Client
  - [ ] Modify Requests And Response

## gRPC implementation

- [ ] add authorization
  - [ ] Register Application
  - [ ] Register Client
  - [ ] Check Client and Application before logging 

- [ ] add reading logging functions

## Web API

- [ ] Create basic schema (OpenAPI)
- [ ] add reading logging functions
